name: dax_flutter
description: It is a flutter package that providers dynamic update solution for flutter developers based on Dax.
version: 1.0.0+1
homepage: https://github.com/juopian/flutter-dax
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dax: ^1.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  package_info_plus: ^1.4.2
  logger: ^1.4.0
  intl: ^0.17.0
  webview_flutter: ^2.8.0
  url_launcher: ^6.1.2
  geolocator: ^7.6.0
  image_picker: ^0.7.5+2
  open_file: ^3.2.1
  path_provider: ^2.0.2
  path: ^1.8.0
  charts_flutter: ^0.12.0
  charts_common: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true